import type { Metadata } from 'next';
import localFont from 'next/font/local';
import Footer from '../components/Footer';
import './globals.css';

const loResFont = localFont({
  src: './../public/fonts/LoRes21OTSerif-Regular.ttf',
});

export const metadata: Metadata = {
  title: 'Celebrity AI',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${loResFont.className} bg-[#212127]`}>
        {children}

        <Footer />
      </body>
    </html>
  );
}
